### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by davephillips** [Phal-anx/MS-Modules#1]
Greetings,

Building for VCV Rack 0.3.2 I get this error :

$ make
g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/RandomSource.cpp.o src/RandomSource.cpp
src/RandomSource.cpp: In member function ‘virtual void RandomSource::step()’:
src/RandomSource.cpp:47:42: error: redeclaration of ‘float range’
  float clock = getf(inputs[TRIG_INPUT]), range;
                                          ^
src/RandomSource.cpp:44:8: note: ‘float range’ previously declared here
  float range = noise * params[RANGE_PARAM] / 20;
        ^
src/RandomSource.cpp:44:8: warning: unused variable ‘range’ [-Wunused-variable]
../../compile.mk:49: recipe for target 'build/src/RandomSource.cpp.o' failed
make: *** [build/src/RandomSource.cpp.o] Error 1

System is Linux, Fedora 21, GCC 4.9.2, all rather old, I know.

Best,

Dave Phillips

**Comment by Phal-anx** [comment]
Hello,

I checked the code and found a small error ( comma instead of a +). its fixed, now it should work properly.

**Comment by davephillips** [comment]
Thanks, that fixed the build. Now I have to figure out how to use the module. :) (I'm rather new to modular synthesis).
