### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by asbaklm** [Phal-anx/MS-Modules#3]
I had to make some changes to get it to build

mv MS-Modules MS_modules

edit Mult.cpp and change #include to:
#include "MS_modules.hpp"

**Comment by Phal-anx** [comment]
i know i made this mistake in an older release but in the current source code for 0.4.0 it was fixed

**Comment by asbaklm** [comment]
I pulled latest git a few mins ago, it seemed to contain that issue?

**Comment by Phal-anx** [comment]
thats wierd... i just tried it myself and i didnt have the same issue and could actually build it right away

anyway.. at least you could solve the issue ;)

**Comment by asbaklm** [comment]
Yeah not sure what's going on. I deleted the MS-Modules code folder from plugins, then just checked it out again just now via git like so:

git clone https://github.com/Phal-anx/MS-Modules.git

It still seems to have the same issues I reported. 
Dunno if my version being pulled from git differs from what you're getting for some weird reason.

**Comment by Phal-anx** [comment]
another way if you get it wrong in future release via git clone.. check it on the website if the error is also in the current files here.. 
something wierd is going on here :D 
anyway have fun with my modules..
