### ISSUE TITLE
Fails to build on current git version of VCVRack

### ISSUE THREAD

**Issue by asbaklm** [Phal-anx/MS-Modules#5]
src/Mult.cpp: In constructor ‘MultWidget::MultWidget()’:
src/Mult.cpp:159:11: error: ‘createValueLight’ was not declared in this scope
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(23, 19), &module->lights[0]));
           ^
src/Mult.cpp:159:39: error: ‘GreenRedPolarityLight’ was not declared in this scope
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(23, 19), &module->lights[0]));
                                       ^
src/Mult.cpp:159:39: error: template argument 1 is invalid
src/Mult.cpp:160:39: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(63, 19), &module->lights[1]));
                                       ^
src/Mult.cpp:159:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(23, 19), &module->lights[0]));
                                       ^
src/Mult.cpp:160:39: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(63, 19), &module->lights[1]));
                                       ^
src/Mult.cpp:160:39: note:   expected a type, got ‘GreenRedPolarityLight’
src/Mult.cpp:161:39: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(103, 19), &module->lights[2]));
                                       ^
src/Mult.cpp:159:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(23, 19), &module->lights[0]));
                                       ^
src/Mult.cpp:161:39: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(103, 19), &module->lights[2]));
                                       ^
src/Mult.cpp:161:39: note:   expected a type, got ‘GreenRedPolarityLight’
src/RandomSource.cpp:28:8: warning: ‘virtual void RandomSource::step()’ can be marked override [-Wsuggest-override]
   void step();
        ^
src/RandomSource.cpp: In constructor ‘RandomSourceWidget::RandomSourceWidget()’:
src/RandomSource.cpp:77:12: error: ‘createValueLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(26, 156), &module->SH_Light));
            ^
src/RandomSource.cpp:77:40: error: ‘GreenRedPolarityLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(26, 156), &module->SH_Light));
                                        ^
src/RandomSource.cpp:77:40: error: template argument 1 is invalid
../../compile.mk:53: recipe for target 'build/src/Mult.cpp.o' failed
make: *** [build/src/Mult.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
src/MS_modules.cpp: In function ‘void init(rack::Plugin*)’:
src/MS_modules.cpp:9:10: error: ‘struct rack::Plugin’ has no member named ‘name’
  plugin->name = "MS-Modules";
          ^
src/MS_modules.cpp:10:10: error: ‘struct rack::Plugin’ has no member named ‘homepageUrl’
  plugin->homepageUrl = "https://github.com/Phal-anx/MS-Modules";
          ^
src/MS_modules.cpp:11:74: error: no matching function for call to ‘createModel(rack::Plugin*&, const char [14], const char [14])’
  createModel<RandomSourceWidget>(plugin, "Random Source", "Random Source");
                                                                          ^
In file included from src/MS_modules.hpp:1:0,
                 from src/MS_modules.cpp:1:
../../include/rack.hpp:22:8: note: candidate: template<class TModuleWidget, class ... Tags> rack::Model* rack::createModel(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, Tags ...)
 Model *createModel(std::string manufacturer, std::string slug, std::string name, Tags... tags) {
        ^
../../include/rack.hpp:22:8: note:   template argument deduction/substitution failed:
src/MS_modules.cpp:11:74: note:   cannot convert ‘plugin’ (type ‘rack::Plugin*’) to type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
  createModel<RandomSourceWidget>(plugin, "Random Source", "Random Source");
                                                                          ^
src/MS_modules.cpp:12:48: error: no matching function for call to ‘createModel(rack::Plugin*&, const char [5], const char [5])’
  createModel<MultWidget>(plugin, "Mult", "Mult");
                                                ^
In file included from src/MS_modules.hpp:1:0,
                 from src/MS_modules.cpp:1:
../../include/rack.hpp:22:8: note: candidate: template<class TModuleWidget, class ... Tags> rack::Model* rack::createModel(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, Tags ...)
 Model *createModel(std::string manufacturer, std::string slug, std::string name, Tags... tags) {
        ^
../../include/rack.hpp:22:8: note:   template argument deduction/substitution failed:
src/MS_modules.cpp:12:48: note:   cannot convert ‘plugin’ (type ‘rack::Plugin*’) to type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
  createModel<MultWidget>(plugin, "Mult", "Mult");
                                                ^
../../compile.mk:53: recipe for target 'build/src/RandomSource.cpp.o' failed
make: *** [build/src/RandomSource.cpp.o] Error 1
../../compile.mk:53: recipe for target 'build/src/MS_modules.cpp.o' failed
make: *** [build/src/MS_modules.cpp.o] Error 1

**Comment by Phal-anx** [comment]
i didnt have time to update for the latest dev version .. its still 0.4.0 
i will update it in the next days
